executable = /home/rcherukuri/quantizing-lsa/scripts/submission_scripts/export_gla/export_gla.sh
arguments = /home/rcherukuri/quantizing-lsa/checkpoints/gla_mod
initialdir = /home/rcherukuri/quantizing-lsa
error = /home/rcherukuri/quantizing-lsa/logs/export_gla/export_gla.err
output = /home/rcherukuri/quantizing-lsa/logs/export_gla/export_gla.out
log = /home/rcherukuri/quantizing-lsa/logs/export_gla/export_gla.log

request_memory = 64000
request_cpus = 8
request_gpus = 4
queue